name: Security and Quality Scan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  code_quality_and_security_scan:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Python dependencies
        run: |
          pip install flake8 bandit

      - name: Run Bandit for security issues
        run: bandit -r .

      - name: Run Flake8 for code quality
        run: flake8 .

  build_and_scan_image:
    needs: code_quality_and_security_scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-application .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "my-application"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
